# Deployment da aplicação web
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec: 
  replicas: 6
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
        - name: conversao-temperatura
          image: jcqueiroz/conversao-temperatura:v1
          ports: 
            - containerPort: 5000
--- 
# Service da aplicação web
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec: 
  selector:
    app: conversao-temperatura
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 32766
  type: NodePort